stages:
  - analysis

# Job para ejecutar el an치lisis de contratos inteligentes
analysis_job:
  stage: analysis
  image: python:3.10  # Usa una imagen con Python 3.10 o la versi칩n necesaria
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt  # Instala dependencias
    - apt-get update
    - apt-get install -y python3-tk
  script:
    - python src/ci_analysis.py  # Ejecuta el an치lisis sin GUI
  artifacts:
    paths:
      - reports/ci_report.json  # Guarda el reporte como artefacto para revisi칩n
    expire_in: 1 week
